name: 'Get terraform version'
description: 'Get terraform version from .terraform-version file'
branding:
  icon: link
  color: purple
inputs:
  path:
    description: 'where to run terraform command'
    required: false
    default: '.'
outputs:
  terraform-version:
    description: "detected terraform version"
    value: ${{ steps.get-terraform-version.outputs.terraform-version }}
runs:
  using: composite
  steps:
    - id: get-terraform-version
      run: |
        result=$(${{ GITHUB_ACTION_PATH }}/src/main.sh ${{ inputs.path }})
        echo "terraform-version=$result" >> $GITHUB_OUTPUT
      shell: bash
